### ISSUE TITLE
Received two DMs after goal set cancelling, expected none

### ISSUE THREAD

**Issue by kipz** [atomist/atomist-sdm#196]
I cancelled a goalset because I'd quickly corrected an issue and pushed it whilst the previous one was still building, and I got two DM's about a failure, but really it was cancelled.

At the very least, I think I should only get the one.

![Screenshot_20190626_101917](https://user-images.githubusercontent.com/1865026/60167865-db19d700-97fb-11e9-824c-b9ff653f5b1a.png)

**Comment by cdupuis** [comment]
Issue moved to atomist/sdm-core#177
