### ISSUE TITLE
Separate linting into its own goal, so that publish can still happen

### ISSUE THREAD

**Issue by jessitron** [atomist/atomist-sdm#49]

**Comment by jessitron** [comment]
We do want linting to fail a goal, but it doesn't need to be the build goal. I still want to test my branch even if it has linting errors.

**Comment by ddgenome** [comment]
While this makes sense for cosmetic linting errors, it seems undesirable for logic errors like unhandled promises, not all paths returning something, etc.

**Comment by jessitron** [comment]
If we want to break those out into two separate linting steps, this is possible.
Lint failures will still prevent merge to master, so I don't see any danger here

**Comment by ddgenome** [comment]
I'm going to try to address this as part of cleaning up the tslint.json autofix debacle.

**Comment by ddgenome** [comment]
In talking with @cdupuis we have come up with a plan that we think satisfies everyone's goals here:

1.  Update the default tslint.json to something more agreeable to everyone
2.  Set up a AutoCodeInspection to create issue for failing lint
3.  Move the code inspection after publish so build and publish occur regardless of its result

Some notes:

-   `reviewListenerRegistration`
-   sdm-pack-issue has `singleIssuePerCategoryManaging()` which may need modified to run on all branches

**Comment by ddgenome** [comment]
Some notes:

-   When @jessitron was setting up automatic TSLint earlier, using it as a library was _way_ slower than using the CLI, so use the CLI with JSON output for now
-   Going to use the "standard" version of TSlint and its config, i.e., the one from this project
-   [sdm-pack-spring](https://github.com/atomist/sdm-pack-spring/blob/master/lib/spring/inspect/springBootVersionInspection.ts) has an example of a code inspection
-   [CodeInspection types](https://github.com/atomist/sdm/blob/1a49e07898a16ad0c7f8f0a659deee57736001f3/lib/api/registration/CodeInspectionRegistration.ts)

**Comment by ddgenome** [comment]
I've pushed my initial implementation: https://github.com/atomist/atomist-sdm/compare/tslint-code-inspection-49

@cdupuis is there an example of setting up a `reviewListenerRegistration` somewhere?

**Comment by cdupuis** [comment]
@ddgenome take a look at 
https://github.com/atomist/sdm-pack-spring/blob/master/lib/spring.ts#L132 

Is that what you are looking for?
