### ISSUE TITLE
The third-party license autofix seems confused by pre-release versions

### ISSUE THREAD

**Issue by ddgenome** [atomist/atomist-sdm#60]
When you replace a released version with a pre-release version, the pre-release version is added to the list of packages rather than replacing the released version.

See https://github.com/atomist/sdm/commit/e0626688d359404e3aa4ee6a53dc81674ef1571a and https://github.com/atomist/sdm/commit/61a4438cff90ce1f04e132189aa45ed038f13a13.

**Comment by cdupuis** [comment]
I wonder if that is because we don't dedupe dependencies we have in our projects when creating the list.

**Comment by ddgenome** [comment]
Interesting. I guess it is not wrong to have them both in there then.

Maybe the versions aren't important as long as the various installed versions have the same license.
